<?php
  include("connection.php");
  //Get the code from the Url and receive the email from the database according to the code
  if(!isset($_GET["code"])){
    echo "<script> alert('Code can not be found please try again later')
    
    window.location.href='../index.php'
    
    </script>";
  }else{
      $con=Database::getInstance()->getConnection();
      $code=$_GET['code'];
      //Doesn't need injection since user can not input the code it is randomly generated by uniqid() method.
      $query=mysqli_query($con,"SELECT email FROM resetPassword WHERE code='$code'");
      if(mysqli_num_rows($query)==0){
        echo "<script> alert('Page can not be found please try again later')
    
        window.location.href='../index.php'
        
        </script>";
      }
  }

  //if password is set just encrypt it, prevent sql injection and update the selected customer row.
  if(isset($_POST["password"]))
  {
      $password= $_POST["password"];
      $encrypted=password_hash($password,PASSWORD_DEFAULT);
      $row= mysqli_fetch_array($query);
      $email=$row['email'];
      $email=mysqli_real_escape_string($con,$email);
      $encrypted=mysqli_real_escape_string($con,$encrypted);
      $query=mysqli_query($con,"UPDATE customers SET password='$encrypted' WHERE email='$email'");
      if($query)
      {
          $queryDelete= mysqli_query($con,"DELETE FROM resetPassword WHERE code=$code");
          echo "<script> alert('Password Updated!!')
    
    window.location.href='../index.php'
    
    </script>";

      }
      else{
        echo "<script> alert('Something went wrong!!')
    
        window.location.href='../index.php'
        
        </script>";
      }
  }
?>
<form method="POST">
<input type="password" name="password" placeholder="New Password">

<br>
<input type="submit" name="submit"  value="Update Password">


</form>



